### ISSUE TITLE
Caixa Econômica - Desenvolver layout

### ISSUE THREAD

**Issue by negherbon** [s2way/cnab240-nodejs#1]
Estamos com uma necessidade aqui na empresa e a idéia é desenvolver o arquivo de remessa para a Caixa Econômica Federal. Só por curiosidade você já está desenvolvendo isso ou posso adicionar mais esse layout pra gente?

Obrigado.

**Comment by exZ** [comment]
Olá, Rafael,

no momento, estamos focados no arquivo de remessa de pagamento do Bradesco,
não temos planos de adicionar arquivos da Caixa. Infelizmente, o build está
quebrado, somente os testes do Retorno.coffee estão passando. A extração
das respostas do arquivo de retorno também não está documentada - é preciso
informar campos de extração no Constants.coffee da operação.

Entretanto, acredito que seja simples implementar uma nova operação de um
novo banco. Você pode fazer um fork, adicionar alterações que quiser e
criar um pull request, porém como estamos em fase de homologação com o
Bradesco, só poderei fazer merge se (1) não houver alterações
significativas nos arquivos Remessa e Retorno ou (2) quando conseguir
revisar e ter certeza de que o layout do Bradesco operando 100%, blz?

De qualquer forma, será uma grande contribuição para o projeto se você
adicionar a Caixa!

Sinta-se à vontade para perguntar caso surjam dúvidas.

Até mais,

-- 

*André Meirelles* | Desenvolvimento – Software Developer
Versul Tecnologia Ltda.
Rua Marcílio Dias, 1659, Centro, Novo Hamburgo - RS
+55 (51) 3066-2613

On Mon, Oct 16, 2017 at 11:01 PM, Rafael Negherbon <notifications@github.com

**Comment by negherbon** [comment]
@exZ desculpa a demora, obrigado pela resposta. Como a nossa necessidade é bem especifica desenvolvemos um próprio e por questão de produtividade deixamos bem hard coded ainda mas estamos trabalhando pra deixar ele mais organizado e liberar open source o quanto antes :)
